
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jun 27 13:46:20 ART 2024
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Si = 8;
  public static final int Fin = 4;
  public static final int Numero = 20;
  public static final int Punto_y_Coma = 18;
  public static final int Entero = 7;
  public static final int Identificador = 19;
  public static final int Parentesis_Abierto = 16;
  public static final int Inicio = 3;
  public static final int Coma = 12;
  public static final int Programa = 2;
  public static final int Variables = 5;
  public static final int Funcion = 6;
  public static final int Sino = 10;
  public static final int EOF = 0;
  public static final int Entonces = 9;
  public static final int Parentesis_Cerrado = 17;
  public static final int error = 1;
  public static final int Dos_Puntos = 15;
  public static final int Modulo = 11;
  public static final int Asignacion = 14;
  public static final int Igual = 13;
    static int Error;
}

